# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\005protoP\001',
  serialized_pb=b'\n\nbase.proto\x12\x05proto\"\xe1\x01\n\nErrorProto\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.proto.ErrorProto.Code\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"\x9b\x01\n\x04\x43ode\x12\x14\n\x10INVALID_ARGUMENT\x10\x00\x12\x11\n\rINVALID_STATE\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x03\x12\r\n\tCANCELLED\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05\x12\x0c\n\x08IO_ERROR\x10\x06\x12\x0f\n\x0bGRPC_STATUS\x10\x62\x12\x0c\n\x08INTERNAL\x10\x63\"\x0b\n\tVoidProto\"_\n\x0cVoidResponse\x12!\n\x05value\x18\x01 \x01(\x0b\x32\x10.proto.VoidProtoH\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.proto.ErrorProtoH\x00\x42\x08\n\x06\x65ither\"\x1b\n\nInt32Proto\x12\r\n\x05value\x18\x01 \x01(\x05\"N\n\rInt32Response\x12\x0f\n\x05value\x18\x01 \x01(\x05H\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.proto.ErrorProtoH\x00\x42\x08\n\x06\x65ither\"\x1b\n\nInt64Proto\x12\r\n\x05value\x18\x01 \x01(\x03\"N\n\rInt64Response\x12\x0f\n\x05value\x18\x01 \x01(\x03H\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.proto.ErrorProtoH\x00\x42\x08\n\x06\x65ither\"\x1c\n\x0bStringProto\x12\r\n\x05value\x18\x01 \x01(\t\"c\n\x0eStringResponse\x12#\n\x05value\x18\x01 \x01(\x0b\x32\x12.proto.StringProtoH\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.proto.ErrorProtoH\x00\x42\x08\n\x06\x65ither\"\x1a\n\tBoolProto\x12\r\n\x05value\x18\x01 \x01(\x08\"_\n\x0c\x42oolResponse\x12!\n\x05value\x18\x01 \x01(\x0b\x32\x10.proto.BoolProtoH\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.proto.ErrorProtoH\x00\x42\x08\n\x06\x65itherB\t\n\x05protoP\x01\x62\x06proto3'
)



_ERRORPROTO_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='proto.ErrorProto.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_ARGUMENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_STATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_EXISTS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IO_ERROR', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRPC_STATUS', index=7, number=98,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL', index=8, number=99,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=92,
  serialized_end=247,
)
_sym_db.RegisterEnumDescriptor(_ERRORPROTO_CODE)


_ERRORPROTO = _descriptor.Descriptor(
  name='ErrorProto',
  full_name='proto.ErrorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.ErrorProto.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='proto.ErrorProto.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERRORPROTO_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=247,
)


_VOIDPROTO = _descriptor.Descriptor(
  name='VoidProto',
  full_name='proto.VoidProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=260,
)


_VOIDRESPONSE = _descriptor.Descriptor(
  name='VoidResponse',
  full_name='proto.VoidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.VoidResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.VoidResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='either', full_name='proto.VoidResponse.either',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=262,
  serialized_end=357,
)


_INT32PROTO = _descriptor.Descriptor(
  name='Int32Proto',
  full_name='proto.Int32Proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Int32Proto.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=386,
)


_INT32RESPONSE = _descriptor.Descriptor(
  name='Int32Response',
  full_name='proto.Int32Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Int32Response.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.Int32Response.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='either', full_name='proto.Int32Response.either',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=388,
  serialized_end=466,
)


_INT64PROTO = _descriptor.Descriptor(
  name='Int64Proto',
  full_name='proto.Int64Proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Int64Proto.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=495,
)


_INT64RESPONSE = _descriptor.Descriptor(
  name='Int64Response',
  full_name='proto.Int64Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Int64Response.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.Int64Response.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='either', full_name='proto.Int64Response.either',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=497,
  serialized_end=575,
)


_STRINGPROTO = _descriptor.Descriptor(
  name='StringProto',
  full_name='proto.StringProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.StringProto.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=605,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='proto.StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.StringResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.StringResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='either', full_name='proto.StringResponse.either',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=607,
  serialized_end=706,
)


_BOOLPROTO = _descriptor.Descriptor(
  name='BoolProto',
  full_name='proto.BoolProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.BoolProto.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=734,
)


_BOOLRESPONSE = _descriptor.Descriptor(
  name='BoolResponse',
  full_name='proto.BoolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.BoolResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.BoolResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='either', full_name='proto.BoolResponse.either',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=736,
  serialized_end=831,
)

_ERRORPROTO.fields_by_name['code'].enum_type = _ERRORPROTO_CODE
_ERRORPROTO_CODE.containing_type = _ERRORPROTO
_VOIDRESPONSE.fields_by_name['value'].message_type = _VOIDPROTO
_VOIDRESPONSE.fields_by_name['error'].message_type = _ERRORPROTO
_VOIDRESPONSE.oneofs_by_name['either'].fields.append(
  _VOIDRESPONSE.fields_by_name['value'])
_VOIDRESPONSE.fields_by_name['value'].containing_oneof = _VOIDRESPONSE.oneofs_by_name['either']
_VOIDRESPONSE.oneofs_by_name['either'].fields.append(
  _VOIDRESPONSE.fields_by_name['error'])
_VOIDRESPONSE.fields_by_name['error'].containing_oneof = _VOIDRESPONSE.oneofs_by_name['either']
_INT32RESPONSE.fields_by_name['error'].message_type = _ERRORPROTO
_INT32RESPONSE.oneofs_by_name['either'].fields.append(
  _INT32RESPONSE.fields_by_name['value'])
_INT32RESPONSE.fields_by_name['value'].containing_oneof = _INT32RESPONSE.oneofs_by_name['either']
_INT32RESPONSE.oneofs_by_name['either'].fields.append(
  _INT32RESPONSE.fields_by_name['error'])
_INT32RESPONSE.fields_by_name['error'].containing_oneof = _INT32RESPONSE.oneofs_by_name['either']
_INT64RESPONSE.fields_by_name['error'].message_type = _ERRORPROTO
_INT64RESPONSE.oneofs_by_name['either'].fields.append(
  _INT64RESPONSE.fields_by_name['value'])
_INT64RESPONSE.fields_by_name['value'].containing_oneof = _INT64RESPONSE.oneofs_by_name['either']
_INT64RESPONSE.oneofs_by_name['either'].fields.append(
  _INT64RESPONSE.fields_by_name['error'])
_INT64RESPONSE.fields_by_name['error'].containing_oneof = _INT64RESPONSE.oneofs_by_name['either']
_STRINGRESPONSE.fields_by_name['value'].message_type = _STRINGPROTO
_STRINGRESPONSE.fields_by_name['error'].message_type = _ERRORPROTO
_STRINGRESPONSE.oneofs_by_name['either'].fields.append(
  _STRINGRESPONSE.fields_by_name['value'])
_STRINGRESPONSE.fields_by_name['value'].containing_oneof = _STRINGRESPONSE.oneofs_by_name['either']
_STRINGRESPONSE.oneofs_by_name['either'].fields.append(
  _STRINGRESPONSE.fields_by_name['error'])
_STRINGRESPONSE.fields_by_name['error'].containing_oneof = _STRINGRESPONSE.oneofs_by_name['either']
_BOOLRESPONSE.fields_by_name['value'].message_type = _BOOLPROTO
_BOOLRESPONSE.fields_by_name['error'].message_type = _ERRORPROTO
_BOOLRESPONSE.oneofs_by_name['either'].fields.append(
  _BOOLRESPONSE.fields_by_name['value'])
_BOOLRESPONSE.fields_by_name['value'].containing_oneof = _BOOLRESPONSE.oneofs_by_name['either']
_BOOLRESPONSE.oneofs_by_name['either'].fields.append(
  _BOOLRESPONSE.fields_by_name['error'])
_BOOLRESPONSE.fields_by_name['error'].containing_oneof = _BOOLRESPONSE.oneofs_by_name['either']
DESCRIPTOR.message_types_by_name['ErrorProto'] = _ERRORPROTO
DESCRIPTOR.message_types_by_name['VoidProto'] = _VOIDPROTO
DESCRIPTOR.message_types_by_name['VoidResponse'] = _VOIDRESPONSE
DESCRIPTOR.message_types_by_name['Int32Proto'] = _INT32PROTO
DESCRIPTOR.message_types_by_name['Int32Response'] = _INT32RESPONSE
DESCRIPTOR.message_types_by_name['Int64Proto'] = _INT64PROTO
DESCRIPTOR.message_types_by_name['Int64Response'] = _INT64RESPONSE
DESCRIPTOR.message_types_by_name['StringProto'] = _STRINGPROTO
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
DESCRIPTOR.message_types_by_name['BoolProto'] = _BOOLPROTO
DESCRIPTOR.message_types_by_name['BoolResponse'] = _BOOLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorProto = _reflection.GeneratedProtocolMessageType('ErrorProto', (_message.Message,), {
  'DESCRIPTOR' : _ERRORPROTO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.ErrorProto)
  })
_sym_db.RegisterMessage(ErrorProto)

VoidProto = _reflection.GeneratedProtocolMessageType('VoidProto', (_message.Message,), {
  'DESCRIPTOR' : _VOIDPROTO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.VoidProto)
  })
_sym_db.RegisterMessage(VoidProto)

VoidResponse = _reflection.GeneratedProtocolMessageType('VoidResponse', (_message.Message,), {
  'DESCRIPTOR' : _VOIDRESPONSE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.VoidResponse)
  })
_sym_db.RegisterMessage(VoidResponse)

Int32Proto = _reflection.GeneratedProtocolMessageType('Int32Proto', (_message.Message,), {
  'DESCRIPTOR' : _INT32PROTO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.Int32Proto)
  })
_sym_db.RegisterMessage(Int32Proto)

Int32Response = _reflection.GeneratedProtocolMessageType('Int32Response', (_message.Message,), {
  'DESCRIPTOR' : _INT32RESPONSE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.Int32Response)
  })
_sym_db.RegisterMessage(Int32Response)

Int64Proto = _reflection.GeneratedProtocolMessageType('Int64Proto', (_message.Message,), {
  'DESCRIPTOR' : _INT64PROTO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.Int64Proto)
  })
_sym_db.RegisterMessage(Int64Proto)

Int64Response = _reflection.GeneratedProtocolMessageType('Int64Response', (_message.Message,), {
  'DESCRIPTOR' : _INT64RESPONSE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.Int64Response)
  })
_sym_db.RegisterMessage(Int64Response)

StringProto = _reflection.GeneratedProtocolMessageType('StringProto', (_message.Message,), {
  'DESCRIPTOR' : _STRINGPROTO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.StringProto)
  })
_sym_db.RegisterMessage(StringProto)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), {
  'DESCRIPTOR' : _STRINGRESPONSE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.StringResponse)
  })
_sym_db.RegisterMessage(StringResponse)

BoolProto = _reflection.GeneratedProtocolMessageType('BoolProto', (_message.Message,), {
  'DESCRIPTOR' : _BOOLPROTO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.BoolProto)
  })
_sym_db.RegisterMessage(BoolProto)

BoolResponse = _reflection.GeneratedProtocolMessageType('BoolResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOLRESPONSE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:proto.BoolResponse)
  })
_sym_db.RegisterMessage(BoolResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
